2025-09-22 00:48:11,068 INFO    MainThread:451533 [wandb_setup.py:_flush():80] Current SDK version is 0.21.0
2025-09-22 00:48:11,068 INFO    MainThread:451533 [wandb_setup.py:_flush():80] Configure stats pid to 451533
2025-09-22 00:48:11,068 INFO    MainThread:451533 [wandb_setup.py:_flush():80] Loading settings from /home/aiotlab/.config/wandb/settings
2025-09-22 00:48:11,068 INFO    MainThread:451533 [wandb_setup.py:_flush():80] Loading settings from /mnt/disk1/aiotlab/hieupc/New_CBraMod/BIOT/wandb/settings
2025-09-22 00:48:11,068 INFO    MainThread:451533 [wandb_setup.py:_flush():80] Loading settings from environment variables
2025-09-22 00:48:11,068 INFO    MainThread:451533 [wandb_init.py:setup_run_log_directory():703] Logging user logs to ./wandb/run-20250922_004811-5feoqg9l/logs/debug.log
2025-09-22 00:48:11,068 INFO    MainThread:451533 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to ./wandb/run-20250922_004811-5feoqg9l/logs/debug-internal.log
2025-09-22 00:48:11,068 INFO    MainThread:451533 [wandb_init.py:init():830] calling init triggers
2025-09-22 00:48:11,068 INFO    MainThread:451533 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-09-22 00:48:11,068 INFO    MainThread:451533 [wandb_init.py:init():871] starting backend
2025-09-22 00:48:11,274 INFO    MainThread:451533 [wandb_init.py:init():874] sending inform_init request
2025-09-22 00:48:11,278 INFO    MainThread:451533 [wandb_init.py:init():882] backend started and connected
2025-09-22 00:48:11,280 INFO    MainThread:451533 [wandb_init.py:init():953] updated telemetry
2025-09-22 00:48:11,285 INFO    MainThread:451533 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-09-22 00:48:12,445 INFO    MainThread:451533 [wandb_init.py:init():1029] starting run threads in backend
2025-09-22 00:48:12,662 INFO    MainThread:451533 [wandb_run.py:_console_start():2458] atexit reg
2025-09-22 00:48:12,662 INFO    MainThread:451533 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-09-22 00:48:12,663 INFO    MainThread:451533 [wandb_run.py:_redirect():2375] Wrapping output streams.
2025-09-22 00:48:12,663 INFO    MainThread:451533 [wandb_run.py:_redirect():2398] Redirects installed.
2025-09-22 00:48:12,664 INFO    MainThread:451533 [wandb_init.py:init():1075] run started, returning control to user process
2025-09-22 00:48:38,669 INFO    MsgRouterThr:451533 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-09-22 00:48:41,249 ERROR   MainThread:451533 [redirect.py:_on_write():664] [all runs] error in stdout callback
Traceback (most recent call last):
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2379, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-09-22 00:48:41,306 ERROR   MainThread:451533 [redirect.py:_on_write():664] [all runs] error in stdout callback
Traceback (most recent call last):
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2379, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-09-22 00:48:41,307 ERROR   MainThread:451533 [redirect.py:_on_write():664] [all runs] error in stdout callback
Traceback (most recent call last):
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2379, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/mnt/disk1/aiotlab/envs/hieupcvp/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
